#### MgF2 coated Quartz retarder

Current example is uncoated; coating to be added

In [1]:
# %matplotlib inline
# %matplotlib tk
# %matplotlib qt5
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
#
import PyAstroPol as pap
pap.roundOffDisplay(5)

In [60]:
Wave = 0.6328
S = pap.Source(4, Clear=10)                                  # Source for ray analysis
Sd = pap.Source(4, Clear=10)                                  # Source for display
S.Wavelength = Sd.Wavelength = Wave
D = pap.Detector(100)                                           # Rotate the detector
D.translateOrigin(z=1000)                                       # Move the detector
#


In [61]:
Dia, Thick = 100, 0.1
Surf1 = pap.Surface(Dia, n1='Air', n2='Quartz', Interference=True)
Surf2 = pap.Surface(Dia, n1='Quartz', n2='Air', Interference=True)
Surf2.translateOrigin(z=Thick)
Surf1.propagateRays(S)
Surf2.propagateRays(Surf1.tRays)

c:\Users\Pruthvi\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


In [62]:
Cover = pap.Material('Air')
Substrate = pap.Material('Air')
FM_Cover, ACover = pap.getBerremanFieldMatrixIsotropic(Cover.getRefractiveIndexAt(Wave), Surf1.Beta)
IFM_Cover = pap.getInverseMatrix(FM_Cover)
FM_Substrate, ASubstrate = pap.getBerremanFieldMatrixIsotropic(Substrate.getRefractiveIndexAt(Wave), Surf1.Beta)
#
IFM_Cover = pap.flattenMatrix(IFM_Cover)
FM_Substrate = pap.flattenMatrix(FM_Substrate)

In [63]:
FM1 = Surf1.FieldMatrix
PM1 = pap.getBerremanPhaseMatrix(Surf1.Alpha, Thick)
IFM1 = pap.getInverseMatrix(FM1)
#
FM1 = pap.flattenMatrix(FM1)
PM1 = pap.flattenMatrix(PM1)
IFM1 = pap.flattenMatrix(IFM1)
#
CM1 = IFM_Cover*FM1*PM1*IFM1*FM_Substrate

In [64]:
CM1

matrix([[array([[0.80891485+0.58792596j],
                [0.80891485+0.58792596j],
                [0.80891485+0.58792596j],
                [0.80891485+0.58792596j]]),
         array([[5.55111512e-17-0.00042072j],
                [5.55111512e-17-0.00042072j],
                [5.55111512e-17-0.00042072j],
                [5.55111512e-17-0.00042072j]]), array([[0.+0.j],
                                                       [0.+0.j],
                                                       [0.+0.j],
                                                       [0.+0.j]]),
         array([[0.+0.j],
                [0.+0.j],
                [0.+0.j],
                [0.+0.j]])],
        [array([[-5.55111512e-17+0.00042072j],
                [-5.55111512e-17+0.00042072j],
                [-5.55111512e-17+0.00042072j],
                [-5.55111512e-17+0.00042072j]]),
         array([[0.80891485-0.58792596j],
                [0.80891485-0.58792596j],
                [0.80891485-0.58792596j],
       